import Head from "next/head";
import {
  Brain,
  Code,
  GithubLogo,
  LinkedinLogo,
  Monitor,
  TwitterLogo,
} from "@phosphor-icons/react";

import { Header } from "@/components/Header";
import { SkillCard } from "@/components/SkillCard";
import { Testimonials } from "@/components/Testimonials";
import { SocialMediaButton } from "@/components/Header/Nav/SocialMediaButtton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Henrique Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main className="overflow-auto pt-40 flex flex-col">
        <div className="flex max-w-6xl m-auto">
          <div className="flex flex-1 flex-col gap-4">
            <SkillCard
              name="Design Thinking"
              icon={<Brain />}
              description="Pensamento crítico e criativo para resolver problemas."
            />
            <SkillCard
              name="Front-end"
              icon={<Monitor />}
              description="Desenvolvimento de interfaces web e mobile."
            />
            <SkillCard
              name="Back-end"
              icon={<Code />}
              description="Desenvolvimento de aplicações web e mobile."
            />
          </div>
          <div className="flex flex-1 flex-col px-32 space-y-8">
            <h5 className="font-tech text-neutral-500">Introdução</h5>
            <h1 className="text-4xl font-medium font-tech">
              Olá! meu nome é Henrique
            </h1>
            <h2 className="text-xl font-medium ">
              “Quando tudo estiver parecendo ir contra você, lembre-se que o
              avião decola contra o vento, e não a favor dele. - Henry Ford
            </h2>
            <p className="font-tech text-neutral-500">
              Entrando cedo na área de tecnologia, desde pequeno sempre tive uma
              paixão por computadores e tecnologia em geral, o que começou como
              hobby se tornou profissão. Desde então, venho me dedicando a
              aprender e aprimorar minhas habilidades na área de desenvolvimento
              de software.
            </p>
          </div>
        </div>
        {/* <section className="flex flex-col max-w-6xl w-full m-auto mt-16">
            <Testimonials />
          </section> */}
        <footer className="flex flex-col w-full bg-neutral-800 px-8 mt-20">
          <div className="flex flex-row w-full max-w-6xl m-auto py-20 justify-between">
            <div className="flex flex-col w-1/2">
              <article>
                <h1 className="text-4xl font-tech">
                  Vamos construir algo incrível juntos.
                </h1>
                <h2 className="text-4xl mt-16">
                  Comece{" "}
                  <a
                    href="https://wa.me/5511964780550"
                    className="mt-8 text-green-400 underline cursor-pointer"
                  >
                    dizendo olá!
                  </a>
                </h2>
              </article>
              <article className="flex justify-between mt-40 items-baseline">
                <h1 className="text-2xl">
                  Henrique <span className="text-neutral-400">Carvalho</span>
                </h1>
                <span className="text-neutral-500">
                  &#169; {new Date().getFullYear()}. Todos o direitos reservados
                </span>
              </article>
            </div>
            <div className="flex flex-col w-1/4 justify-between">
              <article className="flex flex-col">
                <h3 className="text-neutral-500">Informação</h3>
                <h2 className="text-neutral-500 text-xl mt-10">
                  Franco da Rocha, SP - Brasil
                </h2>
                <span className="text-4xl font-tech mt-2">
                  heenriquecds@gmail.com
                </span>
              </article>
              <article className="flex space-x-2">
                <SocialMediaButton
                  icon={<GithubLogo />}
                  alt=""
                  href="https://github.com/HeenriqueCDS"
                />
                <SocialMediaButton
                  icon={<LinkedinLogo />}
                  alt=""
                  href="https://www.linkedin.com/in/henriquecds"
                />
                <SocialMediaButton
                  icon={<TwitterLogo />}
                  alt=""
                  href="https://twitter.com/henriquecdsx"
                />
              </article>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
