import { Header } from "@/components/Header";

import { SkillCard } from "@/components/SkillCard";
import { Brain, Code, Monitor } from "@phosphor-icons/react";
import Head from "next/head";

import { Testimonials } from "@/components/Testimonials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Henrique Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main className="overflow-auto py-40 flex flex-col">
        <div className="flex max-w-6xl m-auto">
          <div className="flex flex-1 flex-col gap-4">
            <SkillCard
              name="Design Thinking"
              icon={<Brain />}
              description="Pensamento crítico e criativo para resolver problemas."
            />
            <SkillCard
              name="Front-end"
              icon={<Monitor />}
              description="Desenvolvimento de interfaces web e mobile."
            />
            <SkillCard
              name="Back-end"
              icon={<Code />}
              description="Desenvolvimento de aplicações web e mobile."
            />
          </div>
          <div className="flex flex-1 flex-col px-32 space-y-8">
            <h5 className="font-tech text-neutral-500">Introdução</h5>
            <h1 className="text-4xl font-medium font-tech">
              Olá! meu nome é Henrique
            </h1>
            <h2 className="text-xl font-medium ">
              “Quando tudo estiver parecendo ir contra você, lembre-se que o
              avião decola contra o vento, e não a favor dele. - Henry Ford
            </h2>
            <p className="font-tech text-neutral-500">
              Entrando cedo na área de tecnologia, desde pequeno sempre tive uma
              paixão por computadores e tecnologia em geral, o que começou como
              hobby se tornou profissão. Desde então, venho me dedicando a
              aprender e aprimorar minhas habilidades na área de desenvolvimento
              de software.
            </p>
          </div>
        </div>
        <section className="flex flex-col max-w-6xl w-full m-auto mt-16">
          <Testimonials />
        </section>
      </main>
    </>
  );
}
