import Head from "next/head";
import Image from "next/image";
import { Brain, Code, Monitor } from "@phosphor-icons/react";

import { Header } from "@/components/Header";
import { SkillCard } from "@/components/SkillCard";
import { SocialMediaButton } from "@/components/Header/Nav/SocialMediaButtton";

import me from "@/assets/me.jpg";
import react from "@/assets/react.png";
import node from "@/assets/nodejs.png";
import python from "@/assets/python.png";
import { Footer } from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Henrique Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className=" bg-neutral-800 px-8">
        <Header />
        <div className="flex flex-row max-w-6xl m-auto mt-8">
          <div className="flex flex-1 flex-col justify-between py-6">
            <section className="flex flex-col md:ml-auto w-80 gap-4">
              <span className="bg-green-400 w-fit p-1 rounded text-neutral-800">
                Fullstack Software Engineer
              </span>
              <h1 className="font-tech text-4xl">
                Falar é fácil, me mostre o código
              </h1>
              <p className="font-tech text-neutral-500">
                Programo desde os 12 anos de idade, desenvolvo aplicações
                escaláveis e com código limpo sempre com foco na entrega de
                valor para o negócio
              </p>
              <a
                href="https://wa.me/5511964780550"
                className="mt-8 text-green-400 underline cursor-pointer font-tech"
              >
                FALE COMIGO!
              </a>
            </section>
            <div className="flex flex-col sm:flex-row mt-32 space-y-8 sm:space-y-0 sm:space-x-10 font-tech">
              <article className="flex flex-row items-center">
                <span className="text-4xl mr-4 font-medium">02</span>
                <p className="text-neutral-500">
                  ANOS DE
                  <br />
                  EXPERIÊNCIA
                </p>
              </article>
              <article className="flex flex-row items-center">
                <span className="text-4xl mr-4 font-medium">+10</span>
                <p className="text-neutral-500">CERFITICAÇÕES</p>
              </article>
            </div>
          </div>
          <div className="flex flex-1 relative items-center justify-center">
            <Image
              src={me}
              alt="Henrique"
              className="hidden md:flex z-10 rounded-full min-h-[300px] min-w-[300px]  lg:h-[500px] md:w-[500px] border-2 border-green-400 object-cover"
            />
            <div className="hidden orbit1 absolute lg:flex items-center justify-center h-24 w-24 z-30 bg-[#141414] rounded-full m-auto">
              <Image
                src={react}
                alt="React icon"
                className="flex h-[60%] w-fit"
              />
            </div>
            <div className="hidden orbit2 absolute lg:flex items-center justify-center h-24 w-24 z-30 bg-[#141414] rounded-full m-auto">
              <Image
                src={node}
                alt="Node Icon"
                className="rotate-[-120deg] h-[60%] w-fit"
              />
            </div>
            <div className="hidden orbit3 absolute lg:flex  items-center justify-center h-24 w-24 z-30 bg-[#141414] rounded-full m-auto">
              <Image
                src={python}
                alt="Python icon"
                className="rotate-[-240deg]  h-[60%] w-fit"
              />
            </div>
          </div>
        </div>
      </div>
      <main className="overflow-auto pt-40 flex flex-col">
        <div className="flex max-w-6xl m-auto px-8 xl:px-0 flex-col md:flex-row">
          <div className="flex flex-1 flex-col gap-4">
            <SkillCard
              name="Design Thinking"
              icon={<Brain />}
              description="Pensamento crítico e criativo para resolver problemas."
            />
            <SkillCard
              name="Front-end"
              icon={<Monitor />}
              description="Desenvolvimento de interfaces web e mobile."
            />
            <SkillCard
              name="Back-end"
              icon={<Code />}
              description="Desenvolvimento de aplicações web e mobile."
            />
          </div>
          <div className="flex flex-1 flex-col mt-20 md:mt-0 px-8 lg:px-32 space-y-8">
            <h5 className="font-tech text-neutral-500">Introdução</h5>
            <h1 className="text-4xl font-medium font-tech">
              Olá! meu nome é Henrique
            </h1>
            <h2 className="text-xl font-medium ">
              “Quando tudo estiver parecendo ir contra você, lembre-se que o
              avião decola contra o vento, e não a favor dele. - Henry Ford
            </h2>
            <p className="font-tech text-neutral-500">
              Entrando cedo na área de tecnologia, desde pequeno sempre tive uma
              paixão por computadores e tecnologia em geral, o que começou como
              hobby se tornou profissão. Desde então, venho me dedicando a
              aprender e aprimorar minhas habilidades na área de desenvolvimento
              de software.
            </p>
          </div>
        </div>
        {/* <section className="flex flex-col max-w-6xl w-full m-auto mt-16">
            <Testimonials />
          </section> */}
        <Footer />
      </main>
    </>
  );
}
