import { Header } from "@/components/Header";
import Head from "next/head";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Henrique Dev: My Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="h-screen overflow-auto">
        <Header />
      </main>
    </>
  );
}
